spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: dev
    password: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: 1234

api:
  host: http://localhost:${server.port}
  gateway:
    dmz: https://test-gateway-site-dmz.sogaz.ru
  payment:
    paymentUrl: ${api.host}/payment/pay/
    sbpPaymentUrl: ${api.host}/payment/paySbp/
    akbUrl: ${api.gateway.dmz}/payment/akb/order
    akbSbpUrl: ${api.gateway.dmz}/payment/akb/order
    akbUrlStatus: ${api.gateway.dmz}/payment/akb/order
    callbackUrlSbp: https://example.com/callback
    merchantIdSbpGpb:
    paymentAccount:
    mainPortalId:
    mainMerchantId:
    depersonalizedPortalId:
    depersonalizedMerchantId:
    backUrlS: http://test.k835.sogaz.ru/realty/flat/success/
    backUrlF: http://test.k835.sogaz.ru/realty/flat/
  receipt:
    receiptUrl: http://s00-0000-k835.sogaz.ru/test/payment-receipt-service
  qr:
    baseUrl: https://s00-0000-k835.sogaz.ru/test/qr-generator-service
  gpb:
    card:
      basePath: ${api.gateway.dmz}/payment/gpb/card/
    sbp:
      basePath: ${api.gateway.dmz}/payment/gpb/sbp/merchant

crons:
  waitingPaymentsCheck: "*/30 * * * * *"
  callbackPaymentsCheck: "*/10 * * * * *"

app:
  rabbit:
    exchange: payments.exchange
    queue-status-payment: payment.status.queue
    routing-key-status-payment: payment.status.created
  gpb:
    certs: ${GPB_CERT:"qx1LDt7avZ2mtsMIiR3EJSrfy30%2BO7LCYEuaHaQ486ofy5K6V1eXvRoKiQxYxnUOJk39bOTA%2F3TfGsnrjVOPD1CjCsulQbsCIDg9Topx7fUQrcS%2BeEv5MBY6V23LtzJVy4SOf6bYf7ABueRlCsMKjI9e7FunnIizJyU%2BWcTTjsBoYvVy5GvI%2FDc%2BwamLvZtQrlWNhyAkodSU6oUmHOIdqw4z0nZZ5YMQ49kwcmjqSqjL3dCHJDe5PQi9yCVj6w6JBX6NUmSaF7MU4GGUrZMr%2FXWXQT5cYxoX18Mfmsz%2BCCosb1otRRkPy1mBRI8kA%2BqcoUbs%2BGV5p8MiS14hWMJXvw%3D%3D"}
    callback_url: https://test-pay.sogaz.ru/payment/gpb/state

logstash:
  host: localhost
  port: 12201
  level: INFO
  level_local: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: localhost
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  server:
    port: 8091
  health:
    livenessState:
      enable: true
    readinessState:
      enable: true