app:
  info:
    application_name: ${PROJECT_NAME:app service}
    version: ${PROJECT_VERSION:1.0.0}
    description: ${PROJECT_DESCRIPTION:Payment Service}
    artifact_Id: ${PROJECT_ARTIFACTID:payment-service}
    group_Id: ${PROJECT_GROUPID:ru.sogaz.site}
    app_profile: ${ENVIRONMENT:dev}
    java-version: ${JAVA_VERSION:21}
  certs:
    gpb: ${GPB_CERT:123}

server:
  port: ${SERVER_PORT:8080}
  use-forward-headers: true
  forward-headers-strategy: framework
  main.allow-bean-definition-overriding: true

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    template:
      routing-key: ${RABBIT_QUEUE:payment.queue}
    queue:
      name: ${RABBIT_QUEUE:payment.queue}
  application:
    name: payment-service
  profiles:
    active: ${ENVIRONMENT:dev}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
    enabled: true
  output:
    ansi:
      enabled: ALWAYS

api:
  payment:
    paymentUrl: ${PAYMENT_URL:URL}
    gpbUrl: ${GPB_URL:https://lt.pga.gazprombank.ru/api/v4/}
    portalId: ${GPB_PORTAL_ID:5BAE2814BB16ED0AA4A146AA4A4E168D}
    merchantId: ${GPB_MERCHANT_ID:B80540E3096C8730BCE3}
    backUrlS: ${BACK_URL_SUCCESS:http://test.k835.sogaz.ru/realty/flat/success/}
    backUrlF: ${BACK_URL_FALSE:https:http://test.k835.sogaz.ru/realty/flat/}
  receipt:
    receiptUrl: ${RECEIPT_URL:http://s00-0000-k835.sogaz.ru/test/payment-receipt-service/paymentCheck/create}
    receiptPath: ${RECEIPT_PATH:/paymentCheck/create}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${HOSTNAME:localhost}
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  server:
    port: ${MANAGEMENT_SERVICE_PORT:8091}
  health:
    livenessState:
      enable: true
    readinessState:
      enable: true

logging:
  level:
    ru:
      sogaz:
        site:
          pattern: ${LOGGING_LEVEL_RU_SOGAZ_ESB:DEBUG}
