spring:
  application:
    name: payment-service
  profiles:
    active: ${ENVIRONMENT:dev}
server:
  port: ${SERVER_PORT:8080}
  use-forward-headers: true
  main.allow-bean-definition-overriding: true
datasource:
  url: jdbc:postgresql://localhost:5432/PostgreSQL_17
  username: postgres
  password: 123456
  driver-class-name: org.postgresql.Driver
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      show_sql: true
liquibase:
  enabled: true
  change-log: classpath:/db/changelog/master-changelog.xml

app:
  info:
    application_name: @project.name@
    version: @project.version@
    description: @project.description@
    artifact_Id: @project.artifactId@
    group_Id: @project.groupId@
    app_profile: ${ENVIRONMENT:dev}
    java-version: @java.version@
api:
  payment-url: ${PAYMENT_URL:url}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${HOSTNAME:localhost}


logging:
  level:
    ru:
      sogaz:
        esb:
          pattern: ${LOGGING_LEVEL_RU_SOGAZ_ESB:DEBUG}